import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FiArrowLeft, FiShield, FiFileText } from 'react-icons/fi';
import Button from '../../components/common/Button.jsx';

/**
 * Enterprise Terms and Conditions page for TransitOps
 */
export const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0B0F19] text-slate-800 dark:text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-10 shadow-sm space-y-8">
        
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-slate-900 dark:bg-white text-white dark:text-slate-900 flex items-center justify-center font-bold">
              <FiFileText className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
                Terms and Conditions
              </h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                Last updated: October 2026 • TransitOps Operations Platform
              </p>
            </div>
          </div>

          <Button
            variant="outline"
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 self-start sm:self-auto text-xs"
          >
            <FiArrowLeft className="w-3.5 h-3.5" /> Back
          </Button>
        </div>

        {/* Content */}
        <div className="space-y-6 text-sm leading-relaxed text-slate-600 dark:text-slate-300">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the TransitOps Fleet Operations Platform ("Service"), you agree to be bound by these Terms and Conditions. If you are entering into these terms on behalf of a company or organization, you represent that you have the authority to bind such entity.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">2. User Accounts & Authorized Access</h2>
            <p>
              Access to operational dashboards, vehicle tracking, trip scheduling, and financial ledgers is restricted to authorized personnel. You are responsible for safeguarding your login credentials and for all activities that occur under your account.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">3. Fleet & Telemetry Data Ownership</h2>
            <p>
              Your organization retains all rights, title, and interest in and to all fleet records, odometer readings, driver profiles, and trip telemetry uploaded to or generated by the platform. TransitOps processes this data solely to provide operations services.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">4. Compliance with Transport Laws</h2>
            <p>
              Users are responsible for ensuring that all driver licenses, vehicle registrations, inspection certificates, and dispatch schedules comply with applicable local, state, and national transportation safety regulations.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">5. Service Availability & Maintenance</h2>
            <p>
              We strive to provide continuous platform availability. Scheduled maintenance and system enhancements will be conducted with prior notice whenever possible.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 dark:text-white">6. Contact Information</h2>
            <p>
              For inquiries regarding these Terms, please contact our support team at <span className="font-semibold text-slate-900 dark:text-white">support@transitops.com</span>.
            </p>
          </section>
        </div>

        {/* Footer actions */}
        <div className="pt-6 border-t border-slate-200 dark:border-slate-800 flex justify-between items-center text-xs text-slate-500">
          <span>© {new Date().getFullYear()} TransitOps Logistics Systems</span>
          <Button variant="primary" onClick={() => navigate('/login')} className="text-xs">
            Return to Login
          </Button>
        </div>

      </div>
    </div>
  );
};

export default Terms;
